# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tffg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/ISE/bubble_4/bubble_4.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/ISE/bubble_4/bubble_4.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Xilinx/ISE/bubble_4/bubble_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/grids.coe
add_files C:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/map_1_48.coe
add_files C:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/players.coe
add_files C:/Users/RenYi/Documents/Ry/University/Study/LCDF/project/produce_coe/new_code/coe/menu_about.coe
add_files C:/Users/RenYi/Documents/Ry/University/Study/LCDF/project/produce_coe/new_code/coe/menu_help.coe
add_files C:/Users/RenYi/Documents/Ry/University/Study/LCDF/project/produce_coe/new_code/coe/menu.coe
add_files C:/Users/RenYi/Documents/Ry/University/Study/LCDF/project/produce_coe/new_code/coe/winnera.coe
add_files C:/Users/RenYi/Documents/Ry/University/Study/LCDF/project/produce_coe/new_code/coe/winnerb.coe
add_files C:/Users/RenYi/Documents/Ry/University/Study/LCDF/project/produce_coe/new_code/coe/menu_bubble.coe
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_win0_img/ic_win0_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_win0_img/ic_win0_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_win1_img/ic_win1_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_win1_img/ic_win1_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_about_img/ic_about_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_about_img/ic_about_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_logo_img_1/ic_logo_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_logo_img_1/ic_logo_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_grid_img_1/ic_grid_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_grid_img_1/ic_grid_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_help_img/ic_help_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_help_img/ic_help_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_map_img/ic_map_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_map_img/ic_map_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_menu_img/ic_menu_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_menu_img/ic_menu_img.dcp]
add_files -quiet c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_players_img/ic_players_img.dcp
set_property used_in_implementation false [get_files c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_players_img/ic_players_img.dcp]
read_verilog -library xil_defaultlib {
  C:/Xilinx/ISE/bubble_4/SegmentDecoder.v
  C:/Xilinx/ISE/bubble_4/ShiftReg.v
  C:/Xilinx/ISE/bubble_4/Seg7Remap.v
  C:/Xilinx/ISE/bubble_4/Seg7Decode.v
  C:/Xilinx/ISE/bubble_4/Seg7Device.v
  C:/Xilinx/ISE/bubble_4/win_img.v
  C:/Xilinx/ISE/bubble_4/transform.v
  C:/Xilinx/ISE/bubble_4/players_img.v
  C:/Xilinx/ISE/bubble_4/map_img.v
  C:/Xilinx/ISE/bubble_4/logo_img.v
  C:/Xilinx/ISE/bubble_4/help_img.v
  C:/Xilinx/ISE/bubble_4/about_img.v
  C:/Xilinx/ISE/bubble_4/menu_img.v
  C:/Xilinx/ISE/bubble_4/grid_img.v
  C:/Xilinx/ISE/bubble_4/seg7_device.v
  C:/Xilinx/ISE/bubble_4/music_player.v
  C:/Xilinx/ISE/bubble_4/calc.v
  C:/Xilinx/ISE/bubble_4/ps2_keyboard.v
  C:/Xilinx/ISE/bubble_4/display_vga.v
  C:/Xilinx/ISE/bubble_4/menu.v
  C:/Xilinx/ISE/bubble_4/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/ISE/bubble_4/bubble_4.srcs/constrs_1/new/pinout.xdc
set_property used_in_implementation false [get_files C:/Xilinx/ISE/bubble_4/bubble_4.srcs/constrs_1/new/pinout.xdc]


synth_design -top top -part xc7k160tffg676-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
