# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_about_img/ic_about_img.xci
# IP: The module: 'ic_about_img' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_about_img/ic_about_img_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ic_about_img'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_about_img/ic_about_img.xci
# IP: The module: 'ic_about_img' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ISE/bubble_4/bubble_4.srcs/sources_1/ip/ic_about_img/ic_about_img_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ic_about_img'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
